-- NOTE - ALL of our tables are ADDITIVE, NO UPDATES only INSERTS,
-- This way we maintain the full history of all the things a user or anyone has done

-- What follows are some enum types we declare
-- TODO - We'll need to make sure these are aligned to values in the code

CREATE TYPE deployment_request_status AS ENUM ('requesting', 'requested', 'failed_deployment', 'executed');

CREATE TABLE contract_payloads (
   id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   contract_id  VARCHAR(50),
   payload      TEXT,
   CONSTRAINT   unique_contract_id UNIQUE (contract_id)
);

-- Contract Deployment Member table where we store info about contracts being
-- deployed.
CREATE TABLE contract_deployment_requests (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_id            BIGINT,
    payload_id          INT,
    contract_mgr_addr   CHAR(42),
    status              deployment_request_status,
    gas_limit           BIGINT,
    tx_hash             CHAR(66),
    time_stamp          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (payload_id) REFERENCES contract_payloads(id),
    CONSTRAINT unique_chain_contract_id UNIQUE (chain_id, payload_id)
);

